name: Despliegue a Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Instalar dependencias
        run: npm install

      - name: Construir la aplicación
        run: npm run build

      - name: Configurar Firebase CLI
        run: npm install -g firebase-tools

      - name: Autenticarse en Firebase
        run: npx firebase login:ci --no-localhost

      - name: Desplegar a Firebase
        run: npx firebase deploy --only hosting --token $FIREBASE_TOKEN